math:
  enable: true
  katex:
    enable: false
    autoRender: false
  mathjax:
    enable: true
    options: 
      {
        tex:
          {
            tags: "ams",
            useLabelIds: true,
            inlineMath: [["$", "$"], ['\\(', '\\)']],
            displayMath: [["$$", "$$"], ['\\[', '\\]']],
            processEscapes: true,
            processEnvironments: true,
            autoload: { color: [], colorv2: ["color"] },
            packages: { "[+]": ["noerrors"] },
          },
        options:
          {
            skipHtmlTags:
              ["script", "noscript", "style", "textarea", "pre", "code"],
            ignoreHtmlClass: "tex2jax_ignore",
            processHtmlClass: "tex2jax_process",
          },
        loader: { load: ["input/asciimath", "[tex]/noerrors"] },
      }

pjax:
  enable: true